services:
  spotify-clone-app:
    build: 
      context: .
      target: development
    volumes: 
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=development
      - SHOW_SWAGGER=true
    command: npm run start:dev